jobs:
- name: php-test
  type: runSh
  steps:
    - IN: u14all-testing
    - TASK:
        runtime:
          options:
            imageName: "drydock/u14phpall"
            imageTag: master
        script: 
         - php --version
         - ~/.phpenv/versions/5.6/bin/php -v
         - ~/.phpenv/versions/5.6/bin/phpunit --version
         - ~/.phpenv/versions/7.0/bin/php -v
         - ~/.phpenv/versions/7.0/bin/phpunit --version
         - ~/.phpenv/versions/7.1/bin/php -v
         - ~/.phpenv/versions/7.1/bin/phpunit --version
         - ~/.phpenv/versions/7.2/bin/php -v
         - ~/.phpenv/versions/7.2/bin/phpunit --version

